/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ziyu_ndkupdate_MainActivity */

#ifndef _Included_com_ziyu_ndkupdate_MainActivity
#define _Included_com_ziyu_ndkupdate_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ziyu_ndkupdate_MainActivity
 * Method:    diffApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ziyu_ndkupdate_MainActivity_diffApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

/*
 * Class:     com_ziyu_ndkupdate_MainActivity
 * Method:    patchApk
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ziyu_ndkupdate_MainActivity_patchApk
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
